version: '2'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - ./dist:/dist
  redis:
    image: "redis:4"
  postgres:
    image: "postgres:9"
