version: '2'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - ./dist:/dist
    links:
      - redis
  redis:
    image: "redis:4"
  postgres:
    build:
        context: .
        dockerfile: Dockerfile-postgres
