version: '2'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile-app
    environment:
        - PGUSER=postgres
        - PGDATABASE=kelbillet
        - PGHOST=postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - ./dist:/dist
  redis:
    image: "redis:4"
  postgres:
    build:
        context: .
        dockerfile: Dockerfile-postgres
